### ISSUE TITLE
CUDA libraries not found on build nodes to which darknet_definition is applied 

### ISSUE THREAD

**Issue by furushchev** [tork-a/darknet-release#1]
this package depends on `nvidia-cuda`, which is equivalent to `apt-get install nvidia-cuda-toolkit`.
`nvidia-cuda-toolkit` installs CUDA Version 5.5 which is not up-to-date and does not have compatibility with 6.0 or later on compilation at all.

The possible problems are:

- if other binaries are already compiled with different version of CUDA, it might occur symbol conflict problem
- CUDA from installer (not `apt-get`) is installed at `/usr/local/cuda`, not `/usr` space. so I think we must search cuda libraries and include directory on compile time rather than predefined in here (https://github.com/tork-a/darknet-release/blob/master/patches/CMakeLists.txt#L11-L24)

**Comment by furushchev** [comment]
@k-okada Is there any reason that you disabled searching runtime cuda library on this package compared to my PR in `jsk_3rdparty`?

```bash
if (_CMAKE_DARKNET_EXTRAS_INCLUDED)
   return()
endif()
set(_CMAKE_DARKNET_EXTRAS_INCLUDED)

function(add_darknet_definitions target)
  find_package(CUDA)
  if(CUDA_FOUND)
    include_directories(${CUDA_INCLUDE_DIRS})
    target_compile_definitions(${target} PUBLIC -DGPU)
    # cuDNN
    find_path(CUDNN_INCLUDE_DIR
      NAMES cudnn.h
      PATHS ${CUDA_INCLUDE_DIRS} /usr/local/cuda/include
      PATH_SUFFIXES include)
    get_filename_component(CUDA_LIB_DIR ${CUDA_LIBRARIES} DIRECTORY)
    find_library(CUDNN_LIBRARY
      NAMES cudnn
      PATHS ${CUDNN_LIB_DIR} /usr/local/cuda/lib64)
    if (EXISTS ${CUDNN_INCLUDE_DIR} AND EXISTS ${CUDNN_LIBRARY})
      include_directories(${CUDNN_INCLUDE_DIR})
      target_compile_definitions(${target} PUBLIC -DCUDNN)
    endif()
  endif()
  find_package(OpenCV)
  if(OpenCV_FOUND)
    if ("${OpenCV_VERSION}" VERSION_LESS "3.0.0")
      include_directories(${OpenCV_INCLUDE_DIRS})
      target_compile_definitions(${target} PUBLIC -DOPENCV)
    endif()
  endif()
endfunction()
```

**Comment by k-okada** [comment]
since we want to distribute darknet through the build firm, we need to compile them against nvidia-cuda-toolkit

> if other binaries are already compiled with different version of CUDA, it might occur symbol conflict problem

does this mean if there is a  process A compiled against cuda-8 and process B compiled against cuda-5, you can not run these two different process ?
I can run `darknet` and `/usr/local/cuda-8.0/samples/bin/x86_64/linux/release/mergeSort` same time
```
Thu Jan 26 10:34:21 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro M500M        Off  | 0000:06:00.0     Off |                  N/A |
| N/A   46C    P0    N/A /  N/A |   1013MiB /  2002MiB |     41%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     17770    G   Xorg                                             7MiB |
|    0     17780    C   darknet                                        890MiB |
|    0     17801    C   ...amples/bin/x86_64/linux/release/mergeSort   113MiB |
+-----------------------------------------------------------------------------+
```

**Comment by furushchev** [comment]
> does this mean if there is a process A compiled against cuda-8 and process B compiled against cuda-5, you can not run these two different process ?

e.g.  let `libdarknet` be compiled and linked with CUDA-5, `libA` be compiled and linked with CUDA-8.
If we compile `libB` which depends both on `libdarknet` and `libA`, is `libB` safely compiled and run?

**Comment by k-okada** [comment]
we're assuming users will use deb package for their program, if you want to
compile some of your node by your self you have to very carefully compile
dependent libraries from source code. This is same situation if you wan to
use opencv3 on 14.04 or pcl 1.8.
so does cuda-8 did not provide CUDA_INCLUDE_DIRS and CUDA_NVCC_DEFINITIONS?
does cudnn.h is necessary for darknet?

--
◉ Kei Okada


2017-01-26 10:44 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada OK. I now understand the policy of this package.
So, the problem will be now current dependency does not install any headers for CUDA.
Maybe we must add dependency:
`nvidia-cuda -> nvidia-cuda-dev`.
I'll open a pull request for this to rosdistro.

**Comment by furushchev** [comment]
Opened PR https://github.com/ros/rosdistro/pull/13717
